### ISSUE TITLE
Test suite fails to compile in GHC 8.6

### ISSUE THREAD

**Issue by Taneb** [pa-ba/equivalence#5]
This due to `MonadFail`'s existence:

```
...
[3 of 4] Compiling Data.Equivalence.Monad_Test ( testsuite/tests/Data/Equivalence/Monad_Test.hs, dist/build/test/test-tmp/Data/Equivalence/Monad_Test.o )

testsuite/tests/Data/Equivalence/Monad_Test.hs:79:3: error:
    • No instance for (Control.Monad.Fail.MonadFail
                         (EquivT s (Set Int) Int Data.Functor.Identity.Identity))
        arising from a do statement
        with the failable pattern ‘[cx, cy]’
    • In a stmt of a 'do' block: [cx, cy] <- getClasses [x, y]
      In the second argument of ‘($)’, namely
        ‘do [cx, cy] <- getClasses [x, y]
            combine cx cy
            d <- desc cx
            return (d == Set.fromList [x, y])’
      In the expression:
        runInt
          $ do [cx, cy] <- getClasses [x, y]
               combine cx cy
               d <- desc cx
               return (d == Set.fromList [x, y])
   |
79 |   [cx,cy] <- getClasses [x,y]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

testsuite/tests/Data/Equivalence/Monad_Test.hs:90:3: error:
    • No instance for (Control.Monad.Fail.MonadFail
                         (EquivT s (Set Int) Int Data.Functor.Identity.Identity))
        arising from a do statement
        with the failable pattern ‘[cx, cy, cz]’
    • In a stmt of a 'do' block: [cx, cy, cz] <- getClasses [x, y, z]
      In the second argument of ‘($)’, namely
        ‘do [cx, cy, cz] <- getClasses [x, y, ....]
            combine cx cy
            combine cy cz
            cx === cz’
      In the expression:
        runInt
          $ do [cx, cy, cz] <- getClasses [x, y, ....]
               combine cx cy
               combine cy cz
               cx === cz
   |
90 |   [cx,cy,cz] <- getClasses [x,y,z]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

testsuite/tests/Data/Equivalence/Monad_Test.hs:109:3: error:
    • No instance for (Control.Monad.Fail.MonadFail
                         (EquivT s (Set Int) Int Data.Functor.Identity.Identity))
        arising from a do statement
        with the failable pattern ‘[cx, cy]’
    • In a stmt of a 'do' block: [cx, cy] <- getClasses [x, y]
      In the second argument of ‘($)’, namely
        ‘do let l1 = x : l1'
                l2 = y : l2'
            cls1 <- getClasses l1
            cls2 <- getClasses l2
            [cx, cy] <- getClasses [x, y]
            ....’
      In the expression:
        runInt
          $ do let l1 = x : l1'
                   l2 = y : l2'
               cls1 <- getClasses l1
               cls2 <- getClasses l2
               [cx, cy] <- getClasses [x, y]
               ....
    |
109 |   [cx,cy] <- getClasses [x,y]
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

testsuite/tests/Data/Equivalence/Monad_Test.hs:172:18: error:
    • No instance for (Control.Monad.Fail.MonadFail
                         (EquivT s (Set Int) Int Data.Functor.Identity.Identity))
        arising from a do statement
        with the failable pattern ‘[cx, cy]’
    • In a stmt of a 'do' block: [cx, cy] <- getClasses [x, y]
      In the second argument of ‘($)’, namely
        ‘do cls1 <- mapM getClasses l1
            mapM combineAll cls1
            cls2 <- getClasses l2
            mapM remove cls2
            ....’
      In the expression:
        runInt
          $ do cls1 <- mapM getClasses l1
               mapM combineAll cls1
               cls2 <- getClasses l2
               mapM remove cls2
               ....
    |
172 |                  [cx,cy] <- getClasses [x,y]
    |        
```
